// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleProductInventoryManagement.Persistence.DatabaseContext;

#nullable disable

namespace SimpleProductInventoryManagement.Persistence.Migrations
{
    [DbContext(typeof(ProductDatabaseContext))]
    [Migration("20250813030918_Addproducts")]
    partial class Addproducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SimpleProductInventoryManagement.Domain.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 13, 11, 9, 17, 681, DateTimeKind.Local).AddTicks(7157),
                            Description = "Fruit",
                            Name = "Dragonfruit",
                            Price = 19.99m,
                            Quantity = 100,
                            UpdatedAt = new DateTime(2025, 8, 13, 11, 9, 17, 681, DateTimeKind.Local).AddTicks(7159)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 13, 11, 9, 17, 681, DateTimeKind.Local).AddTicks(7162),
                            Description = "Fruit",
                            Name = "Grapes",
                            Price = 39.99m,
                            Quantity = 400,
                            UpdatedAt = new DateTime(2025, 8, 13, 11, 9, 17, 681, DateTimeKind.Local).AddTicks(7162)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 13, 11, 9, 17, 681, DateTimeKind.Local).AddTicks(7165),
                            Description = "Vegetable",
                            Name = "Carrots",
                            Price = 9.99m,
                            Quantity = 200,
                            UpdatedAt = new DateTime(2025, 8, 13, 11, 9, 17, 681, DateTimeKind.Local).AddTicks(7165)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 13, 11, 9, 17, 681, DateTimeKind.Local).AddTicks(7167),
                            Description = "Vegetable",
                            Name = "Onions",
                            Price = 1.99m,
                            Quantity = 500,
                            UpdatedAt = new DateTime(2025, 8, 13, 11, 9, 17, 681, DateTimeKind.Local).AddTicks(7168)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 13, 11, 9, 17, 681, DateTimeKind.Local).AddTicks(7170),
                            Description = "Fruit",
                            Name = "Mango",
                            Price = 59.99m,
                            Quantity = 480,
                            UpdatedAt = new DateTime(2025, 8, 13, 11, 9, 17, 681, DateTimeKind.Local).AddTicks(7171)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
